package com.project.back_end.models;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Admin entity
 *
 * Represents an administrator in the Smart Clinic Management System.
 * This class is mapped to the "admins" table via JPA/Hibernate.
 *
 * Annotations used:
 * - @Entity: Marks this class as a JPA entity (maps to a DB table).
 * - @Table: Specifies the table name and allows additional table-level settings.
 * - @Id: Marks the primary key field.
 * - @GeneratedValue(strategy = GenerationType.IDENTITY): Uses DB auto-increment for the PK.
 * - @NotNull: Bean validation to ensure field is not null during create/update.
 * - @JsonProperty(access = JsonProperty.Access.WRITE_ONLY): Prevents sensitive data from being serialized in responses.
 */
@Entity
@Table(name = "admins")
public class Admin {

    // 1) Primary Key
    /**
     * Unique identifier for the Admin entity.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // 2) Username
    /**
     * Admin's login username.
     * Must be non-null and unique in the database.
     */
    @NotNull
    @Column(name = "username", nullable = false, unique = true, length = 100)
    private String username;

    // 3) Password (stored/handled as hash at the service layer)
    /**
     * Admin's password for authentication.
     * Marked as WRITE_ONLY so it won't be included in JSON responses.
     * Must be non-null.
     */
    @NotNull
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    @Column(name = "password_hash", nullable = false, length = 255)
    private String password;

    // 4) Constructors
    /**
     * No-argument constructor required by JPA.
     */
    public Admin() {
    }

    /**
     * Convenience constructor.
     * @param id       primary key (nullable for new entities)
     * @param username admin username (non-null)
     * @param password admin password (non-null)
     */
    public Admin(Long id, String username, String password) {
        this.id = id;
        this.username = username;
        this.password = password;
    }

    // 5) Getters and Setters

    /** @return the admin id (primary key) */
    public Long getId() {
        return id;
    }

    /** @param id the primary key to set */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return the admin username */
    public String getUsername() {
        return username;
    }

    /** @param username the admin username to set */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Note: This getter will not be serialized in JSON due to WRITE_ONLY, but
     * it is available inside the application (e.g., service, repository).
     * @return the admin password (hash or plain depending on service handling)
     */
    public String getPassword() {
        return password;
    }

    /** @param password the admin password to set */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * toString intentionally excludes the password for security reasons.
     */
    @Override
    public String toString() {
        return "Admin{" +
                "id=" + id +
                ", username='" + username + '\'' +
                "}";
    }
}