package com.project.back_end.models;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Future;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;

/**
 * Appointment entity
 *
 * Represents a scheduled appointment between a Doctor and a Patient.
 * Mapped to the "appointments" table via JPA/Hibernate.
 */
@Entity
@Table(name = "appointments")
public class Appointment {

    // 1) Primary Key
    /**
     * Unique identifier for each appointment.
     * Auto-generated by the database (IDENTITY strategy).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // 2) Doctor relation
    /**
     * The doctor assigned to this appointment.
     * Many appointments can be linked to one doctor.
     * Must not be null.
     */
    @NotNull
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumn(name = "doctor_id", nullable = false)
    private Doctor doctor;

    // 3) Patient relation
    /**
     * The patient assigned to this appointment.
     * Many appointments can be linked to one patient.
     * Must not be null.
     */
    @NotNull
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumn(name = "patient_id", nullable = false)
    private Patient patient;

    // 4) Appointment time
    /**
     * The date-time when the appointment is scheduled.
     * Must be in the future at creation time.
     */
    @NotNull
    @Future
    @Column(name = "appointment_time", nullable = false)
    private LocalDateTime appointmentTime;

    // 5) Status (int: 0 = Scheduled, 1 = Completed)
    /**
     * Integer status of the appointment.
     * 0 => Scheduled, 1 => Completed (extend as needed).
     */
    @NotNull
    @Column(name = "status", nullable = false)
    private Integer status = 0;

    // Constructors
    /** No-argument constructor required by JPA. */
    public Appointment() {}

    /**
     * Convenience constructor for initializing an appointment.
     */
    public Appointment(Doctor doctor, Patient patient, LocalDateTime appointmentTime, Integer status) {
        this.doctor = doctor;
        this.patient = patient;
        this.appointmentTime = appointmentTime;
        this.status = status;
    }

    // Getters and Setters
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public Doctor getDoctor() { return doctor; }
    public void setDoctor(Doctor doctor) { this.doctor = doctor; }

    public Patient getPatient() { return patient; }
    public void setPatient(Patient patient) { this.patient = patient; }

    public LocalDateTime getAppointmentTime() { return appointmentTime; }
    public void setAppointmentTime(LocalDateTime appointmentTime) { this.appointmentTime = appointmentTime; }

    public Integer getStatus() { return status; }
    public void setStatus(Integer status) { this.status = status; }

    // 6) Helper methods (transient)

    /**
     * Calculates the end time of the appointment by adding one hour
     * to the start time. Not persisted to the database.
     */
    @Transient
    public LocalDateTime getEndTime() {
        if (appointmentTime == null) return null;
        return appointmentTime.plusHours(1);
    }

    /**
     * Extracts only the date (no time) from appointmentTime.
     * Not persisted to the database.
     */
    @Transient
    public LocalDate getAppointmentDate() {
        if (appointmentTime == null) return null;
        return appointmentTime.toLocalDate();
    }

    /**
     * Extracts only the time (no date) from appointmentTime.
     * Not persisted to the database.
     */
    @Transient
    public LocalTime getAppointmentTimeOnly() {
        if (appointmentTime == null) return null;
        return appointmentTime.toLocalTime();
    }

    @Override
    public String toString() {
        return "Appointment{" +
                "id=" + id +
                ", doctorId=" + (doctor != null ? doctor.getId() : null) +
                ", patientId=" + (patient != null ? patient.getId() : null) +
                ", appointmentTime=" + appointmentTime +
                ", status=" + status +
                '}';
    }
}
