package com.project.back_end.models;

import javax.persistence.*;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Patient entity
 *
 * Represents a patient within the Smart Clinic Management System.
 * Persisted to the "patients" table via JPA/Hibernate.
 *
 * Validations:
 * - name: not null, length 3..100
 * - email: not null, must be a valid email
 * - password: not null, min length 6 (WRITE_ONLY in JSON)
 * - phone: not null, exactly 10 digits
 * - address: not null, max length 255
 */
@Entity
@Table(name = "patients")
public class Patient {

    // 1) Primary Key
    /**
     * Unique identifier for each patient.
     * Auto-generated by the database (IDENTITY strategy).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // 2) Patient's full name
    /**
     * Full name of the patient.
     * Required and must be between 3 and 100 characters.
     */
    @NotNull
    @Size(min = 3, max = 100)
    @Column(name = "full_name", nullable = false, length = 100)
    private String name;

    // 3) Email
    /**
     * Patient email address.
     * Required and must conform to a valid email format.
     */
    @NotNull
    @Email
    @Column(name = "email", nullable = false, length = 255, unique = true)
    private String email;

    // 4) Password
    /**
     * Patient password for authentication.
     * Required, minimum 6 characters.
     * Write-only in JSON to avoid exposure in API responses.
     *
     * NOTE: Store a hash at the service layer before persisting.
     */
    @NotNull
    @Size(min = 6)
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    @Column(name = "password_hash", nullable = false, length = 255)
    private String password;

    // 5) Phone
    /**
     * Patient phone number.
     * Required and must be exactly 10 digits (numeric only).
     */
    @NotNull
    @Pattern(regexp = "^[0-9]{10}$", message = "Phone must be exactly 10 digits")
    @Column(name = "phone", nullable = false, length = 10)
    private String phone;

    // 6) Address
    /**
     * Patient address.
     * Required, up to 255 characters.
     */
    @NotNull
    @Size(max = 255)
    @Column(name = "address", nullable = false, length = 255)
    private String address;

    // 7) Constructors

    /** No-argument constructor required by JPA. */
    public Patient() {}

    /** Convenience constructor. */
    public Patient(String name, String email, String password, String phone, String address) {
        this.name = name;
        this.email = email;
        this.password = password;
        this.phone = phone;
        this.address = address;
    }

    // 8) Getters and Setters

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }

    /**
     * Note: This getter will not appear in JSON output due to WRITE_ONLY,
     * but is available inside the application (e.g., service layer).
     */
    public String getPassword() { return password; }
    public void setPassword(String password) { this.password = password; }

    public String getPhone() { return phone; }
    public void setPhone(String phone) { this.phone = phone; }

    public String getAddress() { return address; }
    public void setAddress(String address) { this.address = address; }

    @Override
    public String toString() {
        return "Patient{" +
               "id=" + id +
               ", name='" + name + '\'' +
               ", email='" + email + '\'' +
               ", phone='" + phone + '\'' +
               ", address='" + address + '\'' +
               '}';
    }
}
